import {
  makeGapReducer,
  makeFontReducer,
  makeLinearReducer,
  type ResizeableStyleDefinition,
  type StyleValues,
} from '@/app/utils/fittingAlgorithm';

export function buildHtmlStyleDefinitions(): ResizeableStyleDefinition[] {
  const STAGE = 2;
  return [
    makeGapReducer('html-h1-margin', 'H1 top margin (pt)', 0, 0, 0.8, STAGE, ['html-h2-margin'], null),
    makeGapReducer('html-h2-margin', 'H2 top margin (pt)', 12, 0, 0.8, STAGE, ['html-h3-margin'], 'html-h1-margin'),
    makeGapReducer(
      'html-h3-margin',
      'H3 top margin (pt)',
      10,
      0,
      0.8,
      STAGE,
      ['html-p-margin', 'html-ul-margin'],
      'html-h2-margin',
    ),
    makeGapReducer(
      'html-p-margin',
      'Paragraph top margin (pt)',
      4,
      0,
      0.8,
      STAGE,
      ['html-ul-margin'],
      'html-h3-margin',
    ),
    makeGapReducer(
      'html-ul-margin',
      'List top margin (pt)',
      4,
      0,
      0.8,
      STAGE,
      ['html-li-margin'],
      'html-p-margin',
    ),
    makeGapReducer(
      'html-li-margin',
      'List item top margin (pt)',
      1,
      0,
      0.8,
      STAGE,
      [],
      'html-ul-margin',
    ),
    makeLinearReducer('line-height', 'Line height (ratio)', 1.3, 1.0, 0.05, STAGE),
    makeLinearReducer('page-margin', 'Page margin (px)', 48, 28.5, 2, STAGE),
    makeFontReducer(
      'html-h1-font',
      'H1 font (pt)',
      22,
      8,
      0.5,
      ['html-h2-font'],
      STAGE,
      null,
    ),
    makeFontReducer(
      'html-h2-font',
      'H2 font (pt)',
      14,
      8,
      0.5,
      ['html-h3-font'],
      STAGE,
      'html-h1-font',
    ),
    makeFontReducer(
      'html-h3-font',
      'H3 font (pt)',
      12,
      8,
      0.5,
      ['html-p-font', 'html-ul-font'],
      STAGE,
      'html-h2-font',
    ),
    makeFontReducer(
      'html-p-font',
      'Paragraph font (pt)',
      10,
      6,
      0.5,
      ['html-ul-font'],
      STAGE,
      'html-h3-font',
    ),
    makeFontReducer(
      'html-ul-font',
      'List font (pt)',
      10,
      6,
      0.5,
      ['html-li-font'],
      STAGE,
      'html-p-font',
    ),
    makeFontReducer(
      'html-li-font',
      'List item font (pt)',
      10,
      6,
      0.5,
      [],
      STAGE,
      'html-ul-font',
    ),
    makeFontReducer('footer-font', 'Footer font (pt)', 8, 6, 0.5, [], STAGE, null),
  ];
}

export function buildHtmlCssVars(values: StyleValues): Record<string, string> {
  const v = (key: string, fallback: number) => values[key] ?? fallback;
  return {
    '--rv-html-h1-font': `${v('html-h1-font', 22)}pt`,
    '--rv-html-h1-margin': `${v('html-h1-margin', 0)}pt`,
    '--rv-html-h2-font': `${v('html-h2-font', 14)}pt`,
    '--rv-html-h2-margin': `${v('html-h2-margin', 12)}pt`,
    '--rv-html-h3-font': `${v('html-h3-font', 12)}pt`,
    '--rv-html-h3-margin': `${v('html-h3-margin', 10)}pt`,
    '--rv-html-p-font': `${v('html-p-font', 10)}pt`,
    '--rv-html-p-margin': `${v('html-p-margin', 4)}pt`,
    '--rv-html-ul-font': `${v('html-ul-font', 10)}pt`,
    '--rv-html-ul-margin': `${v('html-ul-margin', 4)}pt`,
    '--rv-html-li-font': `${v('html-li-font', 10)}pt`,
    '--rv-html-li-margin': `${v('html-li-margin', 1)}pt`,
    '--rv-line-height': `${v('line-height', 1.3)}`,
    '--rv-footer-font': `${v('footer-font', 8)}pt`,
    padding: `${v('page-margin', 48)}px`,
  };
}
